markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge  # Enable Rouge syntax highlighting
  syntax_highlighter_opts:
    guess_lang: true  # Allow language guessing for better highlighting
